plugins {
    id 'java-library'
    id 'maven-publish'
}

group = providers.gradleProperty('group').getOrElse('br.gov.es.pmo')
version = providers.gradleProperty('version').getOrElse('2.1.0')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'openpmo-plugin-user-a-identify-interface'
            pom {
                licenses {
                    license {
                        name = 'GNU General Public License v3.0'
                        url = 'https://www.gnu.org/licenses/gpl-3.0.html'
                        distribution = 'repo'
                    }
                }
            }
        }
    }
}

tasks.named('jar') {
    from(rootProject.file('LICENSE')) {
        into 'META-INF'
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
